### ISSUE TITLE
Case sensitive Teams name

### ISSUE THREAD

**Issue by Pylyv** [zerodaycode/WSC-Triforce#7]
When searching by each teams name, if the name is not completely accurate, the search isn't shown.

for e.g. search for "t1" results are shown; search for "mad" no results are shown; search again for "mad lions" no results are shown; once again, search for "madlions" and no results are shown -> only when "MAD Lions" is searched the results are shown

e.g. nº2: search for "bds", no results are shown; search for "BDS" and still no results are shown

The expected behavior is to show all results for the teams that match the text that is added in the input

**Comment by gbm25** [comment]
Right now we search for literal input.
I'm going to add changes to the query and search for that input anywhere in the text, the search will also be insensitive.
